/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bdo.manager;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
/**
 *
 * @author Stefan
 */
public class MainWindow extends javax.swing.JFrame {

    /**
     * Creates new form MainWindow
     */
    public MainWindow() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        guildoverview = new javax.swing.JScrollPane();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        menuPanel = new javax.swing.JPanel();
        mainMenu = new javax.swing.JPanel();
        guildButton = new javax.swing.JButton();
        classesButton = new javax.swing.JButton();
        skillButton = new javax.swing.JButton();
        equipmentButton = new javax.swing.JButton();
        nodewarButton = new javax.swing.JButton();
        guildname = new javax.swing.JLabel();
        guildMenu = new javax.swing.JPanel();
        addMember = new javax.swing.JButton();
        deleteMember = new javax.swing.JButton();
        backMainMenu = new javax.swing.JButton();
        guildname1 = new javax.swing.JLabel();
        addMemberMenu = new javax.swing.JPanel();
        saveMember = new javax.swing.JButton();
        backGuildMenu = new javax.swing.JButton();
        guildname2 = new javax.swing.JLabel();
        guiPanel = new javax.swing.JPanel();
        startscreen = new javax.swing.JPanel();
        background = new javax.swing.JLabel();
        addMemberPanel = new javax.swing.JPanel();
        mDPEquip = new javax.swing.JPanel();
        empty = new javax.swing.JPanel();
        mDPData = new javax.swing.JPanel();
        mDLFirstName = new javax.swing.JLabel();
        mDLLastName = new javax.swing.JLabel();
        mDLLevel = new javax.swing.JLabel();
        mDLClass = new javax.swing.JLabel();
        mDTFirstName = new javax.swing.JTextField();
        mDTLastName = new javax.swing.JTextField();
        mDCClass = new javax.swing.JComboBox<>();
        mDSLevel = new javax.swing.JSpinner();
        mDPArmor = new javax.swing.JPanel();
        helmetLabel = new javax.swing.JLabel();
        earringLabel2 = new javax.swing.JLabel();
        neglaceLabel = new javax.swing.JLabel();
        alchemieLabel = new javax.swing.JLabel();
        armorLabel = new javax.swing.JLabel();
        ringLabel1 = new javax.swing.JLabel();
        shoesLabel = new javax.swing.JLabel();
        glovesLabel = new javax.swing.JLabel();
        mainLabel = new javax.swing.JLabel();
        secondaryLabel = new javax.swing.JLabel();
        awLabel = new javax.swing.JLabel();
        helmetcLabel2 = new javax.swing.JLabel();
        armorcLabel1 = new javax.swing.JLabel();
        armorcLabel2 = new javax.swing.JLabel();
        glovescLabel1 = new javax.swing.JLabel();
        glovescLabel2 = new javax.swing.JLabel();
        helmetcLabel1 = new javax.swing.JLabel();
        shoescLabel1 = new javax.swing.JLabel();
        shoescLabel2 = new javax.swing.JLabel();
        maincLabel1 = new javax.swing.JLabel();
        maincLabel2 = new javax.swing.JLabel();
        secondarycLabel2 = new javax.swing.JLabel();
        secondarycLabel1 = new javax.swing.JLabel();
        earringLabel1 = new javax.swing.JLabel();
        ringLabel2 = new javax.swing.JLabel();
        beltLabel = new javax.swing.JLabel();

        guildoverview.setPreferredSize(new java.awt.Dimension(1024, 576));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        menuPanel.setLayout(new java.awt.CardLayout());

        mainMenu.setBorder(javax.swing.BorderFactory.createTitledBorder("Menu"));

        guildButton.setText("Guild");
        guildButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                guildButtonMouseClicked(evt);
            }
        });

        classesButton.setText("Classes");
        classesButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                classesButtonMouseClicked(evt);
            }
        });

        skillButton.setText("Skills");
        skillButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                skillButtonMouseClicked(evt);
            }
        });

        equipmentButton.setText("Equipment");
        equipmentButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                equipmentButtonMouseClicked(evt);
            }
        });

        nodewarButton.setText("Node War");
        nodewarButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nodewarButtonMouseClicked(evt);
            }
        });

        guildname.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        guildname.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        guildname.setText("ThelynEnnor");

        javax.swing.GroupLayout mainMenuLayout = new javax.swing.GroupLayout(mainMenu);
        mainMenu.setLayout(mainMenuLayout);
        mainMenuLayout.setHorizontalGroup(
            mainMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mainMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainMenuLayout.createSequentialGroup()
                        .addComponent(guildname, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainMenuLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(mainMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nodewarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(guildButton, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(classesButton, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(skillButton, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(equipmentButton, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(78, 78, 78))))
        );
        mainMenuLayout.setVerticalGroup(
            mainMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainMenuLayout.createSequentialGroup()
                .addComponent(guildButton)
                .addGap(18, 18, 18)
                .addComponent(nodewarButton)
                .addGap(22, 22, 22)
                .addComponent(classesButton)
                .addGap(18, 18, 18)
                .addComponent(skillButton)
                .addGap(18, 18, 18)
                .addComponent(equipmentButton)
                .addGap(131, 131, 131)
                .addComponent(guildname, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(213, Short.MAX_VALUE))
        );

        menuPanel.add(mainMenu, "card2");

        guildMenu.setBorder(javax.swing.BorderFactory.createTitledBorder("Guild Menu"));

        addMember.setText("Add Member");
        addMember.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addMemberMouseClicked(evt);
            }
        });

        deleteMember.setText("Delete Member");
        deleteMember.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deleteMemberMouseClicked(evt);
            }
        });

        backMainMenu.setText("Back");
        backMainMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backMainMenuMouseClicked(evt);
            }
        });
        backMainMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backMainMenuActionPerformed(evt);
            }
        });

        guildname1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        guildname1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        guildname1.setText("ThelynEnnor");

        javax.swing.GroupLayout guildMenuLayout = new javax.swing.GroupLayout(guildMenu);
        guildMenu.setLayout(guildMenuLayout);
        guildMenuLayout.setHorizontalGroup(
            guildMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(guildMenuLayout.createSequentialGroup()
                .addGroup(guildMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(guildMenuLayout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addGroup(guildMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(backMainMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(deleteMember)
                            .addComponent(addMember, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(guildMenuLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(guildname1, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        guildMenuLayout.setVerticalGroup(
            guildMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(guildMenuLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(addMember)
                .addGap(18, 18, 18)
                .addComponent(deleteMember)
                .addGap(18, 18, 18)
                .addComponent(backMainMenu)
                .addGap(199, 199, 199)
                .addComponent(guildname1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(209, Short.MAX_VALUE))
        );

        menuPanel.add(guildMenu, "card3");

        addMemberMenu.setBorder(javax.swing.BorderFactory.createTitledBorder("Guild Menu"));

        saveMember.setText("Save");
        saveMember.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                saveMemberMouseClicked(evt);
            }
        });

        backGuildMenu.setText("Back");
        backGuildMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backGuildMenuMouseClicked(evt);
            }
        });
        backGuildMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backGuildMenuActionPerformed(evt);
            }
        });

        guildname2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        guildname2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        guildname2.setText("ThelynEnnor");

        javax.swing.GroupLayout addMemberMenuLayout = new javax.swing.GroupLayout(addMemberMenu);
        addMemberMenu.setLayout(addMemberMenuLayout);
        addMemberMenuLayout.setHorizontalGroup(
            addMemberMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addMemberMenuLayout.createSequentialGroup()
                .addGroup(addMemberMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(addMemberMenuLayout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addGroup(addMemberMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(backGuildMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(saveMember, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(addMemberMenuLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(guildname2, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        addMemberMenuLayout.setVerticalGroup(
            addMemberMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addMemberMenuLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(saveMember)
                .addGap(18, 18, 18)
                .addComponent(backGuildMenu)
                .addGap(240, 240, 240)
                .addComponent(guildname2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(209, Short.MAX_VALUE))
        );

        menuPanel.add(addMemberMenu, "card3");

        guiPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(" "));
        guiPanel.setLayout(new java.awt.CardLayout());

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/wallpaper.jpg"))); // NOI18N

        javax.swing.GroupLayout startscreenLayout = new javax.swing.GroupLayout(startscreen);
        startscreen.setLayout(startscreenLayout);
        startscreenLayout.setHorizontalGroup(
            startscreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1037, Short.MAX_VALUE)
            .addGroup(startscreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(startscreenLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(background)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        startscreenLayout.setVerticalGroup(
            startscreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 576, Short.MAX_VALUE)
            .addGroup(startscreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(startscreenLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(background)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        guiPanel.add(startscreen, "card2");

        mDPEquip.setLayout(new java.awt.CardLayout());

        empty.setBorder(javax.swing.BorderFactory.createTitledBorder("Equipment"));

        javax.swing.GroupLayout emptyLayout = new javax.swing.GroupLayout(empty);
        empty.setLayout(emptyLayout);
        emptyLayout.setHorizontalGroup(
            emptyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 645, Short.MAX_VALUE)
        );
        emptyLayout.setVerticalGroup(
            emptyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 533, Short.MAX_VALUE)
        );

        mDPEquip.add(empty, "card12");

        mDPData.setBorder(javax.swing.BorderFactory.createTitledBorder("Member Data"));

        mDLFirstName.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        mDLFirstName.setText("First Name");

        mDLLastName.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        mDLLastName.setText("Last Name");

        mDLLevel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        mDLLevel.setText("Level");

        mDLClass.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        mDLClass.setText("Class");

        mDCClass.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        mDCClass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mDCClassActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout mDPDataLayout = new javax.swing.GroupLayout(mDPData);
        mDPData.setLayout(mDPDataLayout);
        mDPDataLayout.setHorizontalGroup(
            mDPDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mDPDataLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mDPDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mDPDataLayout.createSequentialGroup()
                        .addGroup(mDPDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(mDLFirstName)
                            .addComponent(mDLClass, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(mDPDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(mDCClass, 0, 183, Short.MAX_VALUE)
                            .addComponent(mDTFirstName)))
                    .addGroup(mDPDataLayout.createSequentialGroup()
                        .addComponent(mDLLevel, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                        .addComponent(mDSLevel, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mDPDataLayout.createSequentialGroup()
                        .addComponent(mDLLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(mDTLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        mDPDataLayout.setVerticalGroup(
            mDPDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mDPDataLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mDPDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mDTFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mDLFirstName))
                .addGap(18, 18, 18)
                .addGroup(mDPDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mDLLastName)
                    .addComponent(mDTLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(mDPDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mDLLevel)
                    .addComponent(mDSLevel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(mDPDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mDLClass)
                    .addComponent(mDCClass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 11, Short.MAX_VALUE))
        );

        mDLFirstName.getAccessibleContext().setAccessibleName("firstName");

        mDPArmor.setBorder(javax.swing.BorderFactory.createTitledBorder("Armor"));

        helmetLabel.setText("Helmet");
        helmetLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        earringLabel2.setText("Earring");
        earringLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        neglaceLabel.setText("Neglace");
        neglaceLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        alchemieLabel.setText("Alchemy Stone");
        alchemieLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        armorLabel.setText("Armor");
        armorLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        ringLabel1.setText("Ring");
        ringLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        shoesLabel.setText("Shoes");
        shoesLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        glovesLabel.setText("Gloves");
        glovesLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        mainLabel.setText("MainWeapon");
        mainLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        secondaryLabel.setText("Secondary Weapon");
        secondaryLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        awLabel.setText("Awakening");
        awLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        helmetcLabel2.setText("jLabel1");
        helmetcLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        armorcLabel1.setText("jLabel1");
        armorcLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        armorcLabel2.setText("jLabel1");
        armorcLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        glovescLabel1.setText("jLabel1");
        glovescLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        glovescLabel2.setText("jLabel1");
        glovescLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        helmetcLabel1.setText("jLabel1");
        helmetcLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        shoescLabel1.setText("jLabel1");
        shoescLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        shoescLabel2.setText("jLabel1");
        shoescLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        maincLabel1.setText("jLabel1");
        maincLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        maincLabel2.setText("jLabel1");
        maincLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        secondarycLabel2.setText("jLabel1");
        secondarycLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        secondarycLabel1.setText("jLabel1");
        secondarycLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        earringLabel1.setText("Earring");
        earringLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        ringLabel2.setText("Ring");
        ringLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        beltLabel.setText("Belt");
        beltLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout mDPArmorLayout = new javax.swing.GroupLayout(mDPArmor);
        mDPArmor.setLayout(mDPArmorLayout);
        mDPArmorLayout.setHorizontalGroup(
            mDPArmorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mDPArmorLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(mDPArmorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mDPArmorLayout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addGroup(mDPArmorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(mDPArmorLayout.createSequentialGroup()
                                .addGroup(mDPArmorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(mDPArmorLayout.createSequentialGroup()
                                        .addComponent(maincLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(maincLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(mDPArmorLayout.createSequentialGroup()
                                        .addComponent(mainLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(awLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(16, 16, 16)
                                .addGroup(mDPArmorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(secondaryLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(mDPArmorLayout.createSequentialGroup()
                                        .addComponent(secondarycLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(secondarycLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(62, 62, 62))
                            .addGroup(mDPArmorLayout.createSequentialGroup()
                                .addGroup(mDPArmorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(ringLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(earringLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(mDPArmorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(mDPArmorLayout.createSequentialGroup()
                                        .addComponent(beltLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(earringLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(mDPArmorLayout.createSequentialGroup()
                                        .addComponent(neglaceLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(ringLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(mDPArmorLayout.createSequentialGroup()
                        .addComponent(helmetLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(armorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(glovesLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22)
                        .addComponent(shoesLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(alchemieLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(mDPArmorLayout.createSequentialGroup()
                        .addComponent(helmetcLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(helmetcLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(armorcLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(armorcLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(glovescLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(glovescLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24)
                        .addComponent(shoescLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(shoescLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        mDPArmorLayout.setVerticalGroup(
            mDPArmorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mDPArmorLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(mDPArmorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(armorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(shoesLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(alchemieLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(glovesLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(helmetLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(mDPArmorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(armorcLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(mDPArmorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(armorcLabel2)
                        .addComponent(glovescLabel1)
                        .addComponent(glovescLabel2)
                        .addComponent(helmetcLabel1)
                        .addComponent(shoescLabel1)
                        .addComponent(shoescLabel2)
                        .addComponent(helmetcLabel2)))
                .addGap(18, 18, 18)
                .addGroup(mDPArmorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ringLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ringLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(neglaceLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(mDPArmorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(earringLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(earringLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(beltLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(mDPArmorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mainLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(awLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(secondaryLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(mDPArmorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(maincLabel1)
                    .addComponent(maincLabel2)
                    .addComponent(secondarycLabel1)
                    .addComponent(secondarycLabel2)))
        );

        javax.swing.GroupLayout addMemberPanelLayout = new javax.swing.GroupLayout(addMemberPanel);
        addMemberPanel.setLayout(addMemberPanelLayout);
        addMemberPanelLayout.setHorizontalGroup(
            addMemberPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addMemberPanelLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(addMemberPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(mDPData, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(mDPArmor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mDPEquip, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        addMemberPanelLayout.setVerticalGroup(
            addMemberPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addMemberPanelLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(addMemberPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mDPEquip, javax.swing.GroupLayout.PREFERRED_SIZE, 556, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(addMemberPanelLayout.createSequentialGroup()
                        .addComponent(mDPData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(mDPArmor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(13, 13, 13))
        );

        guiPanel.add(addMemberPanel, "card4");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(246, 246, 246))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(guiPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 1049, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(menuPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(guiPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(menuPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void guildButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_guildButtonMouseClicked
        guiPanel.removeAll();
        guiPanel.repaint();
        guiPanel.revalidate();
        
        guiPanel.add(guildoverview);
        guiPanel.repaint();
        guiPanel.revalidate();
        
        menuPanel.removeAll();
        menuPanel.repaint();
        menuPanel.revalidate();
        
        menuPanel.add(guildMenu);
        menuPanel.repaint();
        menuPanel.revalidate();
// TODO add your handling code here:
    }//GEN-LAST:event_guildButtonMouseClicked

    private void nodewarButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nodewarButtonMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_nodewarButtonMouseClicked

    private void classesButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_classesButtonMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_classesButtonMouseClicked

    private void skillButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_skillButtonMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_skillButtonMouseClicked

    private void equipmentButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_equipmentButtonMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_equipmentButtonMouseClicked

    private void backMainMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMainMenuMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_backMainMenuMouseClicked

    private void addMemberMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addMemberMouseClicked
        guiPanel.removeAll();
        guiPanel.repaint();
        guiPanel.revalidate();
        
        guiPanel.add(addMemberPanel);
        guiPanel.repaint();
        guiPanel.revalidate();
        
        menuPanel.removeAll();
        menuPanel.repaint();
        menuPanel.revalidate();
        
        menuPanel.add(addMemberMenu);
        menuPanel.repaint();
        menuPanel.revalidate();
    }//GEN-LAST:event_addMemberMouseClicked

    private void deleteMemberMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteMemberMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_deleteMemberMouseClicked

    private void backMainMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backMainMenuActionPerformed
        guiPanel.removeAll();
        guiPanel.repaint();
        guiPanel.revalidate();
        
        guiPanel.add(startscreen);
        guiPanel.repaint();
        guiPanel.revalidate();
        
        menuPanel.removeAll();
        menuPanel.repaint();
        menuPanel.revalidate();
        
        menuPanel.add(mainMenu);
        menuPanel.repaint();
        menuPanel.revalidate();
        // TODO add your handling code here:
    }//GEN-LAST:event_backMainMenuActionPerformed

    private void mDCClassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mDCClassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mDCClassActionPerformed

    private void saveMemberMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_saveMemberMouseClicked
        try {
            DBConnector db = new DBConnector();            
        } catch (SQLException ex) {
            Logger.getLogger(MainWindow.class.getName()).log(Level.SEVERE, null, ex);
        }
        db.addMeasurementData(measurementId, i, Parameter.getValueOfErgebnis(i), Counter.getCounter1(), Counter.getCounter2(), Counter.getCounter3());
    }//GEN-LAST:event_saveMemberMouseClicked

    private void backGuildMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backGuildMenuMouseClicked
        guiPanel.removeAll();
        guiPanel.repaint();
        guiPanel.revalidate();
        
        guiPanel.add(guildoverview);
        guiPanel.repaint();
        guiPanel.revalidate();
        
        menuPanel.removeAll();
        menuPanel.repaint();
        menuPanel.revalidate();
        
        menuPanel.add(guildMenu);
        menuPanel.repaint();
        menuPanel.revalidate();
// TODO add your handling code here:
    }//GEN-LAST:event_backGuildMenuMouseClicked

    private void backGuildMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backGuildMenuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_backGuildMenuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addMember;
    private javax.swing.JPanel addMemberMenu;
    private javax.swing.JPanel addMemberPanel;
    private javax.swing.JLabel alchemieLabel;
    private javax.swing.JLabel armorLabel;
    private javax.swing.JLabel armorcLabel1;
    private javax.swing.JLabel armorcLabel2;
    private javax.swing.JLabel awLabel;
    private javax.swing.JButton backGuildMenu;
    private javax.swing.JButton backMainMenu;
    private javax.swing.JLabel background;
    private javax.swing.JLabel beltLabel;
    private javax.swing.JButton classesButton;
    private javax.swing.JButton deleteMember;
    private javax.swing.JLabel earringLabel1;
    private javax.swing.JLabel earringLabel2;
    private javax.swing.JPanel empty;
    private javax.swing.JButton equipmentButton;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JLabel glovesLabel;
    private javax.swing.JLabel glovescLabel1;
    private javax.swing.JLabel glovescLabel2;
    private javax.swing.JPanel guiPanel;
    private javax.swing.JButton guildButton;
    private javax.swing.JPanel guildMenu;
    private javax.swing.JLabel guildname;
    private javax.swing.JLabel guildname1;
    private javax.swing.JLabel guildname2;
    private javax.swing.JScrollPane guildoverview;
    private javax.swing.JLabel helmetLabel;
    private javax.swing.JLabel helmetcLabel1;
    private javax.swing.JLabel helmetcLabel2;
    private javax.swing.JComboBox<String> mDCClass;
    private javax.swing.JLabel mDLClass;
    private javax.swing.JLabel mDLFirstName;
    private javax.swing.JLabel mDLLastName;
    private javax.swing.JLabel mDLLevel;
    private javax.swing.JPanel mDPArmor;
    private javax.swing.JPanel mDPData;
    private javax.swing.JPanel mDPEquip;
    private javax.swing.JSpinner mDSLevel;
    private javax.swing.JTextField mDTFirstName;
    private javax.swing.JTextField mDTLastName;
    private javax.swing.JLabel mainLabel;
    private javax.swing.JPanel mainMenu;
    private javax.swing.JLabel maincLabel1;
    private javax.swing.JLabel maincLabel2;
    private javax.swing.JPanel menuPanel;
    private javax.swing.JLabel neglaceLabel;
    private javax.swing.JButton nodewarButton;
    private javax.swing.JLabel ringLabel1;
    private javax.swing.JLabel ringLabel2;
    private javax.swing.JButton saveMember;
    private javax.swing.JLabel secondaryLabel;
    private javax.swing.JLabel secondarycLabel1;
    private javax.swing.JLabel secondarycLabel2;
    private javax.swing.JLabel shoesLabel;
    private javax.swing.JLabel shoescLabel1;
    private javax.swing.JLabel shoescLabel2;
    private javax.swing.JButton skillButton;
    private javax.swing.JPanel startscreen;
    // End of variables declaration//GEN-END:variables
}
