/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bdo.manager;

/**
 *
 * @author Stefan
 */
public class MainWindow extends javax.swing.JFrame {

    /**
     * Creates new form MainWindow
     */
    public MainWindow() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        guildoverview = new javax.swing.JScrollPane();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        menuPanel = new javax.swing.JPanel();
        mainMenu = new javax.swing.JPanel();
        guildButton = new javax.swing.JButton();
        classesButton = new javax.swing.JButton();
        skillButton = new javax.swing.JButton();
        equipmentButton = new javax.swing.JButton();
        nodewarButton = new javax.swing.JButton();
        guildname = new javax.swing.JLabel();
        guildMenu = new javax.swing.JPanel();
        addMember = new javax.swing.JButton();
        deleteMember = new javax.swing.JButton();
        backMainMenu = new javax.swing.JButton();
        guildname1 = new javax.swing.JLabel();
        addMemberMenu = new javax.swing.JPanel();
        saveMember = new javax.swing.JButton();
        backGuildMenu = new javax.swing.JButton();
        guildname2 = new javax.swing.JLabel();
        guiPanel = new javax.swing.JPanel();
        startscreen = new javax.swing.JPanel();
        background = new javax.swing.JLabel();
        addMemberPanel = new javax.swing.JPanel();
        mDPEquip = new javax.swing.JPanel();
        empty = new javax.swing.JPanel();
        mDCArmor = new javax.swing.JPanel();
        mDCHelmet = new javax.swing.JPanel();
        mDCGloves = new javax.swing.JPanel();
        mDCShoes = new javax.swing.JPanel();
        mDCRing = new javax.swing.JPanel();
        mDCEarring = new javax.swing.JPanel();
        mDCHelmet6 = new javax.swing.JPanel();
        mDCHelmet7 = new javax.swing.JPanel();
        mDCNeclase = new javax.swing.JPanel();
        mDCMainW = new javax.swing.JPanel();
        mDCSecondaryW = new javax.swing.JPanel();
        mDCAwakened = new javax.swing.JPanel();
        mDCBelt = new javax.swing.JPanel();
        mDPData = new javax.swing.JPanel();
        mDLFirstName = new javax.swing.JLabel();
        mDLLastName = new javax.swing.JLabel();
        mDLLevel = new javax.swing.JLabel();
        mDLClass = new javax.swing.JLabel();
        mDTFirstName = new javax.swing.JTextField();
        mDTLastName = new javax.swing.JTextField();
        mDCClass = new javax.swing.JComboBox<>();
        mDSLevel = new javax.swing.JSpinner();
        mDPArmor = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();

        guildoverview.setPreferredSize(new java.awt.Dimension(1024, 576));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        menuPanel.setLayout(new java.awt.CardLayout());

        mainMenu.setBorder(javax.swing.BorderFactory.createTitledBorder("Menu"));

        guildButton.setText("Guild");
        guildButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                guildButtonMouseClicked(evt);
            }
        });

        classesButton.setText("Classes");
        classesButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                classesButtonMouseClicked(evt);
            }
        });

        skillButton.setText("Skills");
        skillButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                skillButtonMouseClicked(evt);
            }
        });

        equipmentButton.setText("Equipment");
        equipmentButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                equipmentButtonMouseClicked(evt);
            }
        });

        nodewarButton.setText("Node War");
        nodewarButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nodewarButtonMouseClicked(evt);
            }
        });

        guildname.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        guildname.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        guildname.setText("ThelynEnnor");

        javax.swing.GroupLayout mainMenuLayout = new javax.swing.GroupLayout(mainMenu);
        mainMenu.setLayout(mainMenuLayout);
        mainMenuLayout.setHorizontalGroup(
            mainMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mainMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainMenuLayout.createSequentialGroup()
                        .addComponent(guildname, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainMenuLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(mainMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nodewarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(guildButton, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(classesButton, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(skillButton, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(equipmentButton, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(78, 78, 78))))
        );
        mainMenuLayout.setVerticalGroup(
            mainMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainMenuLayout.createSequentialGroup()
                .addComponent(guildButton)
                .addGap(18, 18, 18)
                .addComponent(nodewarButton)
                .addGap(22, 22, 22)
                .addComponent(classesButton)
                .addGap(18, 18, 18)
                .addComponent(skillButton)
                .addGap(18, 18, 18)
                .addComponent(equipmentButton)
                .addGap(131, 131, 131)
                .addComponent(guildname, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(213, Short.MAX_VALUE))
        );

        menuPanel.add(mainMenu, "card2");

        guildMenu.setBorder(javax.swing.BorderFactory.createTitledBorder("Guild Menu"));

        addMember.setText("Add Member");
        addMember.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addMemberMouseClicked(evt);
            }
        });

        deleteMember.setText("Delete Member");
        deleteMember.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deleteMemberMouseClicked(evt);
            }
        });

        backMainMenu.setText("Back");
        backMainMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backMainMenuMouseClicked(evt);
            }
        });
        backMainMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backMainMenuActionPerformed(evt);
            }
        });

        guildname1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        guildname1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        guildname1.setText("ThelynEnnor");

        javax.swing.GroupLayout guildMenuLayout = new javax.swing.GroupLayout(guildMenu);
        guildMenu.setLayout(guildMenuLayout);
        guildMenuLayout.setHorizontalGroup(
            guildMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(guildMenuLayout.createSequentialGroup()
                .addGroup(guildMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(guildMenuLayout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addGroup(guildMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(backMainMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(deleteMember)
                            .addComponent(addMember, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(guildMenuLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(guildname1, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        guildMenuLayout.setVerticalGroup(
            guildMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(guildMenuLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(addMember)
                .addGap(18, 18, 18)
                .addComponent(deleteMember)
                .addGap(18, 18, 18)
                .addComponent(backMainMenu)
                .addGap(199, 199, 199)
                .addComponent(guildname1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(209, Short.MAX_VALUE))
        );

        menuPanel.add(guildMenu, "card3");

        addMemberMenu.setBorder(javax.swing.BorderFactory.createTitledBorder("Guild Menu"));

        saveMember.setText("Save");
        saveMember.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                saveMemberMouseClicked(evt);
            }
        });

        backGuildMenu.setText("Back");
        backGuildMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backGuildMenuMouseClicked(evt);
            }
        });
        backGuildMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backGuildMenuActionPerformed(evt);
            }
        });

        guildname2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        guildname2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        guildname2.setText("ThelynEnnor");

        javax.swing.GroupLayout addMemberMenuLayout = new javax.swing.GroupLayout(addMemberMenu);
        addMemberMenu.setLayout(addMemberMenuLayout);
        addMemberMenuLayout.setHorizontalGroup(
            addMemberMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addMemberMenuLayout.createSequentialGroup()
                .addGroup(addMemberMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(addMemberMenuLayout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addGroup(addMemberMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(backGuildMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(saveMember, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(addMemberMenuLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(guildname2, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        addMemberMenuLayout.setVerticalGroup(
            addMemberMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addMemberMenuLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(saveMember)
                .addGap(18, 18, 18)
                .addComponent(backGuildMenu)
                .addGap(240, 240, 240)
                .addComponent(guildname2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(209, Short.MAX_VALUE))
        );

        menuPanel.add(addMemberMenu, "card3");

        guiPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(" "));
        guiPanel.setLayout(new java.awt.CardLayout());

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/wallpaper.jpg"))); // NOI18N

        javax.swing.GroupLayout startscreenLayout = new javax.swing.GroupLayout(startscreen);
        startscreen.setLayout(startscreenLayout);
        startscreenLayout.setHorizontalGroup(
            startscreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1037, Short.MAX_VALUE)
            .addGroup(startscreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(startscreenLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(background)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        startscreenLayout.setVerticalGroup(
            startscreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 576, Short.MAX_VALUE)
            .addGroup(startscreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(startscreenLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(background)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        guiPanel.add(startscreen, "card2");

        mDPEquip.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout emptyLayout = new javax.swing.GroupLayout(empty);
        empty.setLayout(emptyLayout);
        emptyLayout.setHorizontalGroup(
            emptyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        emptyLayout.setVerticalGroup(
            emptyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        mDPEquip.add(empty, "card12");

        javax.swing.GroupLayout mDCHelmetLayout = new javax.swing.GroupLayout(mDCHelmet);
        mDCHelmet.setLayout(mDCHelmetLayout);
        mDCHelmetLayout.setHorizontalGroup(
            mDCHelmetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 642, Short.MAX_VALUE)
        );
        mDCHelmetLayout.setVerticalGroup(
            mDCHelmetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 546, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout mDCArmorLayout = new javax.swing.GroupLayout(mDCArmor);
        mDCArmor.setLayout(mDCArmorLayout);
        mDCArmorLayout.setHorizontalGroup(
            mDCArmorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mDCHelmet, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        mDCArmorLayout.setVerticalGroup(
            mDCArmorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mDCArmorLayout.createSequentialGroup()
                .addComponent(mDCHelmet, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        mDPEquip.add(mDCArmor, "card2");

        javax.swing.GroupLayout mDCGlovesLayout = new javax.swing.GroupLayout(mDCGloves);
        mDCGloves.setLayout(mDCGlovesLayout);
        mDCGlovesLayout.setHorizontalGroup(
            mDCGlovesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        mDCGlovesLayout.setVerticalGroup(
            mDCGlovesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        mDPEquip.add(mDCGloves, "card2");

        javax.swing.GroupLayout mDCShoesLayout = new javax.swing.GroupLayout(mDCShoes);
        mDCShoes.setLayout(mDCShoesLayout);
        mDCShoesLayout.setHorizontalGroup(
            mDCShoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        mDCShoesLayout.setVerticalGroup(
            mDCShoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        mDPEquip.add(mDCShoes, "card2");

        javax.swing.GroupLayout mDCRingLayout = new javax.swing.GroupLayout(mDCRing);
        mDCRing.setLayout(mDCRingLayout);
        mDCRingLayout.setHorizontalGroup(
            mDCRingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        mDCRingLayout.setVerticalGroup(
            mDCRingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        mDPEquip.add(mDCRing, "card2");

        javax.swing.GroupLayout mDCHelmet7Layout = new javax.swing.GroupLayout(mDCHelmet7);
        mDCHelmet7.setLayout(mDCHelmet7Layout);
        mDCHelmet7Layout.setHorizontalGroup(
            mDCHelmet7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        mDCHelmet7Layout.setVerticalGroup(
            mDCHelmet7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout mDCHelmet6Layout = new javax.swing.GroupLayout(mDCHelmet6);
        mDCHelmet6.setLayout(mDCHelmet6Layout);
        mDCHelmet6Layout.setHorizontalGroup(
            mDCHelmet6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(mDCHelmet6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(mDCHelmet6Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(mDCHelmet7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        mDCHelmet6Layout.setVerticalGroup(
            mDCHelmet6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(mDCHelmet6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(mDCHelmet6Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(mDCHelmet7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout mDCEarringLayout = new javax.swing.GroupLayout(mDCEarring);
        mDCEarring.setLayout(mDCEarringLayout);
        mDCEarringLayout.setHorizontalGroup(
            mDCEarringLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(mDCEarringLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(mDCEarringLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(mDCHelmet6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        mDCEarringLayout.setVerticalGroup(
            mDCEarringLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(mDCEarringLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(mDCEarringLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(mDCHelmet6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        mDPEquip.add(mDCEarring, "card2");

        javax.swing.GroupLayout mDCNeclaseLayout = new javax.swing.GroupLayout(mDCNeclase);
        mDCNeclase.setLayout(mDCNeclaseLayout);
        mDCNeclaseLayout.setHorizontalGroup(
            mDCNeclaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        mDCNeclaseLayout.setVerticalGroup(
            mDCNeclaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        mDPEquip.add(mDCNeclase, "card2");

        javax.swing.GroupLayout mDCMainWLayout = new javax.swing.GroupLayout(mDCMainW);
        mDCMainW.setLayout(mDCMainWLayout);
        mDCMainWLayout.setHorizontalGroup(
            mDCMainWLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        mDCMainWLayout.setVerticalGroup(
            mDCMainWLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        mDPEquip.add(mDCMainW, "card10");

        javax.swing.GroupLayout mDCSecondaryWLayout = new javax.swing.GroupLayout(mDCSecondaryW);
        mDCSecondaryW.setLayout(mDCSecondaryWLayout);
        mDCSecondaryWLayout.setHorizontalGroup(
            mDCSecondaryWLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        mDCSecondaryWLayout.setVerticalGroup(
            mDCSecondaryWLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        mDPEquip.add(mDCSecondaryW, "card11");

        javax.swing.GroupLayout mDCAwakenedLayout = new javax.swing.GroupLayout(mDCAwakened);
        mDCAwakened.setLayout(mDCAwakenedLayout);
        mDCAwakenedLayout.setHorizontalGroup(
            mDCAwakenedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        mDCAwakenedLayout.setVerticalGroup(
            mDCAwakenedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        mDPEquip.add(mDCAwakened, "card12");

        javax.swing.GroupLayout mDCBeltLayout = new javax.swing.GroupLayout(mDCBelt);
        mDCBelt.setLayout(mDCBeltLayout);
        mDCBeltLayout.setHorizontalGroup(
            mDCBeltLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        mDCBeltLayout.setVerticalGroup(
            mDCBeltLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        mDPEquip.add(mDCBelt, "card2");

        mDPData.setBorder(javax.swing.BorderFactory.createTitledBorder("Member Data"));

        mDLFirstName.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        mDLFirstName.setText("First Name");

        mDLLastName.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        mDLLastName.setText("Last Name");

        mDLLevel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        mDLLevel.setText("Level");

        mDLClass.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        mDLClass.setText("Class");

        mDCClass.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        mDCClass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mDCClassActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout mDPDataLayout = new javax.swing.GroupLayout(mDPData);
        mDPData.setLayout(mDPDataLayout);
        mDPDataLayout.setHorizontalGroup(
            mDPDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mDPDataLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mDPDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mDPDataLayout.createSequentialGroup()
                        .addGroup(mDPDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(mDLFirstName)
                            .addComponent(mDLClass, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(mDPDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(mDCClass, 0, 183, Short.MAX_VALUE)
                            .addComponent(mDTFirstName)))
                    .addGroup(mDPDataLayout.createSequentialGroup()
                        .addComponent(mDLLevel, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                        .addComponent(mDSLevel, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mDPDataLayout.createSequentialGroup()
                        .addComponent(mDLLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(mDTLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        mDPDataLayout.setVerticalGroup(
            mDPDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mDPDataLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mDPDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mDTFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mDLFirstName))
                .addGap(18, 18, 18)
                .addGroup(mDPDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mDLLastName)
                    .addComponent(mDTLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(mDPDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mDLLevel)
                    .addComponent(mDSLevel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(mDPDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mDLClass)
                    .addComponent(mDCClass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 11, Short.MAX_VALUE))
        );

        mDLFirstName.getAccessibleContext().setAccessibleName("firstName");

        mDPArmor.setBorder(javax.swing.BorderFactory.createTitledBorder("Armor"));

        jLabel2.setText("Helmet");
        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel3.setText("Earring");
        jLabel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel4.setText("Neclase");
        jLabel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel5.setText("Alchemy Stone");
        jLabel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel6.setText("Armor");
        jLabel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel7.setText("Ring");
        jLabel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel8.setText("Shoes");
        jLabel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel9.setText("Gloves");
        jLabel9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel10.setText("MainWeapon");
        jLabel10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel11.setText("Secondary Weapon");
        jLabel11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel12.setText("Awakening");
        jLabel12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel13.setText("jLabel1");
        jLabel13.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel14.setText("jLabel1");
        jLabel14.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel15.setText("jLabel1");
        jLabel15.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel16.setText("jLabel1");
        jLabel16.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel17.setText("jLabel1");
        jLabel17.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel18.setText("jLabel1");
        jLabel18.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel19.setText("jLabel1");
        jLabel19.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel20.setText("jLabel1");
        jLabel20.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel21.setText("jLabel1");
        jLabel21.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel22.setText("jLabel1");
        jLabel22.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel23.setText("jLabel1");
        jLabel23.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel24.setText("jLabel1");
        jLabel24.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel25.setText("Earring");
        jLabel25.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel26.setText("Ring");
        jLabel26.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel27.setText("Belt");
        jLabel27.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout mDPArmorLayout = new javax.swing.GroupLayout(mDPArmor);
        mDPArmor.setLayout(mDPArmorLayout);
        mDPArmorLayout.setHorizontalGroup(
            mDPArmorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mDPArmorLayout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addGroup(mDPArmorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mDPArmorLayout.createSequentialGroup()
                        .addGroup(mDPArmorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(mDPArmorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(mDPArmorLayout.createSequentialGroup()
                                .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(mDPArmorLayout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(mDPArmorLayout.createSequentialGroup()
                        .addGroup(mDPArmorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(mDPArmorLayout.createSequentialGroup()
                                .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(mDPArmorLayout.createSequentialGroup()
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(16, 16, 16)
                        .addGroup(mDPArmorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(mDPArmorLayout.createSequentialGroup()
                                .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(mDPArmorLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(mDPArmorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(mDPArmorLayout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(mDPArmorLayout.createSequentialGroup()
                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(22, 22, 22)
                .addGroup(mDPArmorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(mDPArmorLayout.createSequentialGroup()
                        .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        mDPArmorLayout.setVerticalGroup(
            mDPArmorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mDPArmorLayout.createSequentialGroup()
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(mDPArmorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(mDPArmorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jLabel16)
                    .addComponent(jLabel17)
                    .addComponent(jLabel18)
                    .addComponent(jLabel19)
                    .addComponent(jLabel20)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addGap(18, 18, 18)
                .addGroup(mDPArmorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(mDPArmorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(mDPArmorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(mDPArmorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(jLabel22)
                    .addComponent(jLabel24)
                    .addComponent(jLabel23)))
        );

        javax.swing.GroupLayout addMemberPanelLayout = new javax.swing.GroupLayout(addMemberPanel);
        addMemberPanel.setLayout(addMemberPanelLayout);
        addMemberPanelLayout.setHorizontalGroup(
            addMemberPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addMemberPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(addMemberPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(mDPData, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(mDPArmor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(mDPEquip, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        addMemberPanelLayout.setVerticalGroup(
            addMemberPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addMemberPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(addMemberPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(mDPEquip, javax.swing.GroupLayout.PREFERRED_SIZE, 557, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(addMemberPanelLayout.createSequentialGroup()
                        .addComponent(mDPData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(mDPArmor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        guiPanel.add(addMemberPanel, "card4");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(246, 246, 246))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(guiPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 1049, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(menuPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(guiPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(menuPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void guildButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_guildButtonMouseClicked
        guiPanel.removeAll();
        guiPanel.repaint();
        guiPanel.revalidate();
        
        guiPanel.add(guildoverview);
        guiPanel.repaint();
        guiPanel.revalidate();
        
        menuPanel.removeAll();
        menuPanel.repaint();
        menuPanel.revalidate();
        
        menuPanel.add(guildMenu);
        menuPanel.repaint();
        menuPanel.revalidate();
// TODO add your handling code here:
    }//GEN-LAST:event_guildButtonMouseClicked

    private void nodewarButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nodewarButtonMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_nodewarButtonMouseClicked

    private void classesButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_classesButtonMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_classesButtonMouseClicked

    private void skillButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_skillButtonMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_skillButtonMouseClicked

    private void equipmentButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_equipmentButtonMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_equipmentButtonMouseClicked

    private void backMainMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMainMenuMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_backMainMenuMouseClicked

    private void addMemberMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addMemberMouseClicked
        guiPanel.removeAll();
        guiPanel.repaint();
        guiPanel.revalidate();
        
        guiPanel.add(addMemberPanel);
        guiPanel.repaint();
        guiPanel.revalidate();
        
        menuPanel.removeAll();
        menuPanel.repaint();
        menuPanel.revalidate();
        
        menuPanel.add(addMemberMenu);
        menuPanel.repaint();
        menuPanel.revalidate();
    }//GEN-LAST:event_addMemberMouseClicked

    private void deleteMemberMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteMemberMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_deleteMemberMouseClicked

    private void backMainMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backMainMenuActionPerformed
        guiPanel.removeAll();
        guiPanel.repaint();
        guiPanel.revalidate();
        
        guiPanel.add(startscreen);
        guiPanel.repaint();
        guiPanel.revalidate();
        
        menuPanel.removeAll();
        menuPanel.repaint();
        menuPanel.revalidate();
        
        menuPanel.add(mainMenu);
        menuPanel.repaint();
        menuPanel.revalidate();
        // TODO add your handling code here:
    }//GEN-LAST:event_backMainMenuActionPerformed

    private void mDCClassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mDCClassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mDCClassActionPerformed

    private void saveMemberMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_saveMemberMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_saveMemberMouseClicked

    private void backGuildMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backGuildMenuMouseClicked
        guiPanel.removeAll();
        guiPanel.repaint();
        guiPanel.revalidate();
        
        guiPanel.add(guildoverview);
        guiPanel.repaint();
        guiPanel.revalidate();
        
        menuPanel.removeAll();
        menuPanel.repaint();
        menuPanel.revalidate();
        
        menuPanel.add(guildMenu);
        menuPanel.repaint();
        menuPanel.revalidate();
// TODO add your handling code here:
    }//GEN-LAST:event_backGuildMenuMouseClicked

    private void backGuildMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backGuildMenuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_backGuildMenuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addMember;
    private javax.swing.JPanel addMemberMenu;
    private javax.swing.JPanel addMemberPanel;
    private javax.swing.JButton backGuildMenu;
    private javax.swing.JButton backMainMenu;
    private javax.swing.JLabel background;
    private javax.swing.JButton classesButton;
    private javax.swing.JButton deleteMember;
    private javax.swing.JPanel empty;
    private javax.swing.JButton equipmentButton;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JPanel guiPanel;
    private javax.swing.JButton guildButton;
    private javax.swing.JPanel guildMenu;
    private javax.swing.JLabel guildname;
    private javax.swing.JLabel guildname1;
    private javax.swing.JLabel guildname2;
    private javax.swing.JScrollPane guildoverview;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel mDCArmor;
    private javax.swing.JPanel mDCAwakened;
    private javax.swing.JPanel mDCBelt;
    private javax.swing.JComboBox<String> mDCClass;
    private javax.swing.JPanel mDCEarring;
    private javax.swing.JPanel mDCGloves;
    private javax.swing.JPanel mDCHelmet;
    private javax.swing.JPanel mDCHelmet6;
    private javax.swing.JPanel mDCHelmet7;
    private javax.swing.JPanel mDCMainW;
    private javax.swing.JPanel mDCNeclase;
    private javax.swing.JPanel mDCRing;
    private javax.swing.JPanel mDCSecondaryW;
    private javax.swing.JPanel mDCShoes;
    private javax.swing.JLabel mDLClass;
    private javax.swing.JLabel mDLFirstName;
    private javax.swing.JLabel mDLLastName;
    private javax.swing.JLabel mDLLevel;
    private javax.swing.JPanel mDPArmor;
    private javax.swing.JPanel mDPData;
    private javax.swing.JPanel mDPEquip;
    private javax.swing.JSpinner mDSLevel;
    private javax.swing.JTextField mDTFirstName;
    private javax.swing.JTextField mDTLastName;
    private javax.swing.JPanel mainMenu;
    private javax.swing.JPanel menuPanel;
    private javax.swing.JButton nodewarButton;
    private javax.swing.JButton saveMember;
    private javax.swing.JButton skillButton;
    private javax.swing.JPanel startscreen;
    // End of variables declaration//GEN-END:variables
}
